markdown: kramdown
permalink: /:year/:month/:title/
highlighter: rouge
lsi: false
base_url: https://graysky.org
my_email: mike@graysky.org
about_page: "mike-champion"
static_pages:
  - archives
  - grindstone
title: mike champion
analytics: UA-287373-2
author :
  name : Mike Champion
  github : graysky
  twitter : graysky
  email: mike@graysky.org