auto: false
markdown: rdiscount
permalink: /:year/:month/:title
destination: ./site
pygments: true
lsi: false
base_url: http://graysky.org
my_email: mike@graysky.org
about_page: "mike-champion"
static_pages: 
  - photography
  - grindstone
  - mike-champion
  - archives